# Generated by Django 3.0.11 on 2020-11-18 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(default=False, verbose_name='isMale')),
                ('dateOfBirth', models.DateField()),
                ('hobby', models.TextField(default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('coverPhoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('timePost', models.DateField(auto_now_add=True)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Group')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Account')),
            ],
        ),
        migrations.CreateModel(
            name='GroupHasAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Group')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Account')),
            ],
        ),
        migrations.CreateModel(
            name='GroupBelongCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('timeComment', models.DateField(auto_now_add=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountReportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('timeReport', models.DateField(auto_now_add=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Post')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Account')),
            ],
        ),
        migrations.CreateModel(
            name='accountReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('timeReport', models.DateField(auto_now_add=True)),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Comment')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountApplyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeApply', models.DateField(auto_now_add=True)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Group')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Account')),
            ],
        ),
    ]
