# Generated by Django 3.0.11 on 2020-11-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dateOfBirth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.TextField(blank=True, default=''),
        ),
    ]
