# Generated by Django 3.0.11 on 2020-11-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201118_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
