# Generated by Django 3.0.11 on 2020-11-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201118_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
